version: 0.2
phases:
  install:
    commands:
    - make init
  build:
    commands:
      echo $CODEBUILD_SRC_DIR
    - make
    - make package
artifacts:
  files:
    - dist/packaged-app.yml
  discard-paths: yes
